cart/urls.py
# urls.py

from django.urls import path
from .views import add_to_cart, view_cart, update_cart_item

urlpatterns = [
    path('cart/add/<int:book_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='view_cart'),
    path('cart/update/<int:item_id>/', update_cart_item, name='update_cart_item'),
]

ebook_store/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
     path("", include("books.urls")),
     path("", include("users.urls")),
     path("", include("cart.urls")),


     # password Change
    path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change'), #as_view is used for class based views cuz passwordchangeview is django builtin vie which is class-based view
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done'), 
    #password Reset
    path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset'), 
    path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'), 
    path('reset/<uidb64>/<token>' , auth_views.PasswordResetConfirmView.as_view() , name='password_reset_confirm'), 
    path('reset/done/' , auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'), 
]
 # there is password manage process given below:

    # password_change
    # password_change_done

    # password_reset
    # password_reset_done
    # password_reset_confirm
    # password_reset_complete

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path("register/", user_register_view, name="user_register_view"),
    path("login/", user_login_view, name="user_login_view"),
    path("logout/", user_logout_view, name="user_logout_view"),
    path("profile/", user_profile_detail_view, name="user_profile_detail_view"),
    path("profile/edit/", user_profile_edit_view, name="user_profile_edit_view"),
    path("users/verify_email/<str:token>/", verify_email_view, name="verify_email"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
   name = models.CharField(max_length = 30 , null=True , blank=True)
   email = models.EmailField(null=True , unique=True)
   is_email_verified = models.BooleanField(default=False)
   email_verification_token = models.CharField(max_length=200 ,blank=True, null=True)

   def __str__(self):
        return self.username

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE , blank=True, null=True)
    name = models.CharField(max_length = 30 , null=True , blank=True)
    username = models.CharField(max_length = 30)
    email = models.EmailField(null=True , unique=True)

    def __str__(self):
        return self.username

class ContactUs(models.Model):
    name = models.CharField(max_length = 20)
    subject = models.CharField(max_length = 20)
    email = models.EmailField(null=False , unique=False)
    message = models.TextField(max_length = 500)

    def __str__(self):
        return self.message

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))

class CommonSignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))
    email = forms.CharField(max_length=30, required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1')

class CustomerSignUpForm(CommonSignUpForm):
    class Meta:
        model = User
        fields = CommonSignUpForm.Meta.fields + ('name',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = "__all__"


users/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from django.contrib.auth import login  , authenticate, logout
from django.contrib import messages
from .forms import LoginForm , CustomerSignUpForm
from .models import *
from .forms import *
import uuid
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required


def user_register_view(request):

    if request.method == 'POST':
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Don't save to the database yet
            user.is_customer = True  # Set any additional attributes if needed
            user.is_staff = False  
            user.is_email_verified = False
            user.email_verification_token = str(uuid.uuid4())
            user.save()  # Save the user using the manager of your custom User model

            # making profile during registration
            profile = UserProfile.objects.create(
                user=user,
                name=user.name,
                username=user.username,
                email=user.email,
            )

            current_site = get_current_site(request)
            subject = 'Activate Your Account'
            activation_link = f'http://{current_site}/users/verify_email/{user.email_verification_token}/'
            message = f'click the link to activate your account:{activation_link}'
            email_from = settings.DEFAULT_FROM_EMAIL
            recipeient_list = [user.email]
            send_mail(subject, message, email_from, recipeient_list)

            messages.success(request, "Thank you for registering! Please check your email to verify your account before logging in.")

            return redirect('users:user_login_view')
        else:
            print("Form is not valid:", form.errors)
    else:
        form = CustomerSignUpForm()
    return render(request , "users/login.html", {'form':form})

def verify_email_view(request , token):
    try:
        user = User.objects.get(email_verification_token = token)
        if user:
           user.is_email_verified = True
           user.email_verification_token = None
           user.save()
           return redirect('users:user_login_view')
    except:
        return HttpResponse("Activation Link is Invalid")

def user_login_view(request):
    msg = None
    if request.method == 'POST':
        form = LoginForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            # Authenticate user
            user = authenticate(username=username, password=password)
            
            if user is not None and user.is_email_verified:
                login(request, user)
                return redirect('books:home_view')
            else:
                messages.success(request, 'Invalid Credentials')
            
        else:   
            print(form.errors)
    else:
        form = LoginForm()
    return render(request , 'users/login.html', {'form':form})

def user_logout_view(request):
    logout(request)
    return redirect('books:home_view')

def user_profile_detail_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    
    return render(request, 'users/profile.html', {'user_profile': user_profile})

@login_required
# Edit Detail view of Profile
def user_profile_edit_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES ,  instance=user_profile)
        if form.is_valid():
            user = form.save(commit=False)
            user_profile.user = request.user  # Ensure the user is set correctly
            user.save()
            user = request.user
            user.name = form.cleaned_data['name']
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            user.save()
            messages.success(request, 'Profile successfully updated.')
            return redirect('users:user_profile_detail_view')
        else:
            print("Form is not valid:", form.errors)
    else:
        form = UserProfileForm(instance=user_profile)

    return render(request, 'users/profile.html', {'form': form})


users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Login & Signup{% endblock title %}
{% block css %}<link rel="stylesheet" href="{% static 'users/css/login.css'%}">{% endblock css %}
{% block content %}
<div class="main-section py-5">
  <section class="wrapper">
    <!--Email Confirmation Message Start-->
    {% if messages %}
    {% for message in messages  %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <i class="fa fa-info-circle" aria-hidden="true"></i> {{message}}
    </div>
    {% endfor %}
    {% endif %}
    <!--Email Confirmation Message End-->
    <div class="form signup">
      <header>Signup</header>
      <form action="{% url 'users:user_register_view' %}"
      method="post"
      enctype="multipart/form-data">
      {% csrf_token %}
        <input type="text" name="name" placeholder="Full name" required />
        {{ form.username.errors }}
        <input type="text" name="username" placeholder="Username" required />
        {{ form.email.errors }}
        <input type="text" name="email" placeholder="Email address" required />
        {{ form.password2.errors }}
        <input type="password" name="password1" placeholder="Password" required />
        <input type="password" name="password2" placeholder="Confirm Password" required />
        <div class="checkbox">
          <input type="checkbox" id="signupCheck" />
          <label for="signupCheck">I accept all terms & conditions</label>
        </div>
        <input type="submit" value="Signup" />
      </form>
    </div>
    <div class="form login">
      <header>Login</header>
      <form action="{% url 'users:user_login_view' %}"
      method="post"
      enctype="multipart/form-data">
      {% csrf_token %}
        {{ form.username.errors }}
        <input type="text" name="username" placeholder="Username" required />
        {{ form.password.errors }}
        <input type="password" name="password" placeholder="Password" required />
        <a href="{% url "password_reset" %}">Forgot password?</a>
        <input type="submit" value="Login" />
      </form>
    </div>
    <script>
      const wrapper = document.querySelector(".wrapper"),
        signupHeader = document.querySelector(".signup header"),
        loginHeader = document.querySelector(".login header");
      loginHeader.addEventListener("click", () => {
        wrapper.classList.add("active");
      });
      signupHeader.addEventListener("click", () => {
        wrapper.classList.remove("active");
      });
    </script>
  </section>
</div>



{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %} 
{% load static %}
{% block title %}Profile{% endblock title %} 
{% block css %}<link rel="stylesheet" href="{% static 'users/css/profile.css'%}">{% endblock css %} 
{% block content %}
<!--Message Start-->
{% if messages %} {% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <i class="fa fa-check-circle" aria-hidden="true"></i> {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %}
<!--Message End-->
{% if user_profile %}
<form
  action="{% url 'users:user_profile_edit_view' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <div class="col-12 bg-body rounded ">
            <div class="row g-2 ms-2 me-2">
              <div class="col-md-12 border-end">
                <div class="p-3 py-5">
                  <div
                    class="d-flex justify-content-between align-items-center"
                  >
                    <h4 class="fw-bold">Profile Settings</h4>
                  </div>
                  <div class="row mt-4">
                    <div class="col-6">
                      <label class="form-label">Name</label>
                      <input
                        type="text"
                        id="first_name"
                        name="name"
                        class="form-control"
                        value="{{user_profile.name}}"
                      />
                    </div>

                    <div class="col-6">
                      <label class="form-label">Username</label>
                      <input
                        type="text"
                        id="username"
                        name="username"
                        class="form-control"
                        value="{{user_profile.username}}"
                      />
                    </div>
                    <div class="col-12">
                      <label class="form-label">Email</label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        class="form-control"
                        value="{{user_profile.email}}"
                      />
                    </div>
                    
                    <div class="col-12 d-grid mt-3">
                      <button class="btn btn-primary" type="submit">
                        Update My Profile
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% else %}
<p>No profile found</p>
{% endif %} {% endblock content %}