books/urls.py
from django.urls import path
from .views import *

app_name = 'books'

urlpatterns = [
    path('', home, name='home_view'),
    path('about/', about, name='about_view'),
    path('contact/', contact, name='contact_view'),
    path('book-list/', book_list, name='book_list'),
]

cart/urls.py
# urls.py

from django.urls import path
from .views import add_to_cart, view_cart, update_cart_item

urlpatterns = [
    path('cart/add/<int:book_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='view_cart'),
    path('cart/update/<int:item_id>/', update_cart_item, name='update_cart_item'),
]

ebook_store/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
     path("", include("books.urls")),
     path("", include("users.urls")),
     path("", include("cart.urls")),


     # password Change
    path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change'), #as_view is used for class based views cuz passwordchangeview is django builtin vie which is class-based view
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done'), 
    #password Reset
    path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset'), 
    path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'), 
    path('reset/<uidb64>/<token>' , auth_views.PasswordResetConfirmView.as_view() , name='password_reset_confirm'), 
    path('reset/done/' , auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'), 
]
 # there is password manage process given below:

    # password_change
    # password_change_done

    # password_reset
    # password_reset_done
    # password_reset_confirm
    # password_reset_complete

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path("register/", user_register_view, name="user_register_view"),
    path("login/", user_login_view, name="user_login_view"),
    path("logout/", user_logout_view, name="user_logout_view"),
    path("profile/", user_profile_detail_view, name="user_profile_detail_view"),
    path("profile/edit/", user_profile_edit_view, name="user_profile_edit_view"),
    path("users/verify_email/<str:token>/", verify_email_view, name="verify_email"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicon -->
  <link href="img/favicon.ico" rel="icon">

  <!-- Google Web Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

  <!-- Icon Font Stylesheet -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

  <!-- Libraries Stylesheet -->
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

  <!-- Customized Bootstrap Stylesheet -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Template Stylesheet -->
  <link href="css/style.css" rel="stylesheet">
  <title>{% block title %}{% endblock title %}</title>
  {% block css %}{% endblock css %}
  {% block javascript %}{% endblock javascript%}
  
</head>
<body>
  {% include "header.html" %}
  {% block content %}
  {% endblock content %}
  {% include "footer.html" %}

  <!-- JavaScript Libraries -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

  <!-- Template Javascript -->
  <script src="{% static 'js/main.js' %}"></script>

  
</body>

</html>

templates/footer.html
{% load static %}
   <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer wow fadeIn" data-wow-delay="0.1s">
      <div class="container py-5">
          <div class="row g-5">
              <div class="col-lg-3 col-md-6">
                  <h4 class="text-white mb-3">Quick Link</h4>
                  <a class="btn btn-link" href="">About Us</a>
                  <a class="btn btn-link" href="">Contact Us</a>
                  <a class="btn btn-link" href="">Privacy Policy</a>
                  <a class="btn btn-link" href="">Terms & Condition</a>
                  <a class="btn btn-link" href="">FAQs & Help</a>
              </div>
              <div class="col-lg-3 col-md-6">
                  <h4 class="text-white mb-3">Contact</h4>
                  <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                  <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                  <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                  <div class="d-flex pt-2">
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                  </div>
              </div>
              <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Gallery</h4>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-1.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-2.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-3.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-2.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-3.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-1.jpg' %}" alt="">
                    </div>
                </div>
            </div>
              <div class="col-lg-3 col-md-6">
                  <h4 class="text-white mb-3">Newsletter</h4>
                  <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                  <div class="position-relative mx-auto" style="max-width: 400px;">
                      <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                      <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                  </div>
              </div>
          </div>
      </div>
      <div class="container">
          <div class="copyright">
              <div class="row">
                  <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                      &copy; <a class="border-bottom" href="#">eBook Store</a>, All Right Reserved.
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Footer End -->

templates/header.html

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="home.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eBook Store</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url "books:home_view" %}" class="nav-item nav-link active">Home</a>
                <a href="{% url "books:about_view" %}" class="nav-item nav-link">About</a>
                <a href="{% url "books:book_list" %}" class="nav-item nav-link">Books</a>
                {% if user.is_authenticated %}
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Settings</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="{% url "users:user_profile_detail_view" %}" class="dropdown-item">Your Profile</a>
                        <a href="{% url "password_change" %}" class="dropdown-item">Change Password</a>
                    </div>
                </div>
                {% endif %}
                <a href="{% url "books:contact_view" %}" class="nav-item nav-link">Contact</a>
            </div>
            {% if user.is_authenticated %}
            <a href="{% url "users:user_logout_view" %}" class="btn btn-danger py-4 px-lg-5 d-none d-lg-block">Logout<i class="fa fa-arrow-left ms-3"></i></a>
            {% else %}
            <a href="{% url "users:user_login_view" %}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Sign up<i class="fa fa-arrow-right ms-3"></i></a>
            {% endif %}
        </div>
    </nav>
    <!-- Navbar End -->